apiVersion: data.packaging.carvel.dev/v1alpha1
kind: Package
metadata:
  name: where-for-dinner-availability.my-apps.tap.20231022024747.0.0+build.02e9424
spec:
  refName: where-for-dinner-availability.my-apps.tap
  version: 20231022024747.0.0+build.02e9424
  releaseNotes: |
    Release v20231022024747.0.0+build.02e9424 of package where-for-dinner-availability.my-apps.tap
  template:
    spec:
      fetch:
      - imgpkgBundle:
          image: dev.registry.tanzu.vmware.com/tanzu-application-platform/ci-pipeline/apps-21-10-2023-22-55-26-068071616/where-for-dinner-availability-my-apps-bundle@sha256:bed2aea7a091fcf57aff6027d380ee7ceeb3223945b092bd790adefe423317e2
      template:
      - ytt:
          paths:
          - .
      - kbld:
          paths:
          - .imgpkg/images.yml
          - '-'
      deploy:
      - kapp: {}
  valuesSchema:
    openAPIv3:
      type: object
      additionalProperties: false
      properties:
        workload_name:
          type: string
          default: ""

